bind:
  http: ":7778"
  udp: ":7776"
oauth:
  redirect_url: "http://localhost:8080/jwt/"
  state_secret: "state-secret"
  jwt_secret: "jwt-secret"
clickhouse: "tcp://127.0.0.1:9000?database=logr&username=logr&password=logr"
mysql: "logr:logr@/logr"