bind:
  http: ":7778"
  udp: ":7776"
oauth:
  jwt_secret: "jwt-secret"
  github: # create OAuth App https://docs.github.com/en/developers/apps/creating-an-oauth-app
    org: ""
    client_id: "client_id"
    client_secret: "client_secret"
clickhouse: "tcp://localhost:9000?database=logr&username=logr&password=logr"
mysql: "logr:logr@/logr"